version: "3.6"

services:
  db:
    image: library/mongo:4.4-bionic
    restart: always
  elastic:
    image: library/elasticsearch:7.8.1
    restart: always
    environment:
      discovery.type: single-node
  cache:
    restart: always
    image: library/memcached:alpine

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    depends_on:
      - db
      - elastic
      - cache
    volumes:
      - "./app:/opt/app"
    restart: always
    ports:
      - "5000:5000"
    working_dir: /opt/app
    entrypoint: ./glass.py run -H 0.0.0.0 -P 5000

  task-server:
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    depends_on:
      - db
      - elastic
      - cache
    volumes:
      - "./app:/opt/app"
    restart: always
    working_dir: /opt/app
    entrypoint: ./glass.py tasks
